// Generated by `npm run brand:apply`. Edit brand/brand.json instead.

export const brandName = "Pitch Unfairly";
export const wordmark = "Pitch Unfairly";
export const logos: Record<string, string> = {  };
export const imagery: { url: string; role: string; alt: string; notes: string }[] = [
];
